export const localStrings = {
  home: 'Home',
  calculations: 'Calculations',
  add: 'Add',
  name: 'Name',
  addExpense: 'Add Expense',
  expenses: 'Expenses',
  calculate: 'Calculate',
  expenseAdded: 'Expense added',
  warning: 'Warning',
  expense: 'Expense',
  substracted: 'Substracted from average',
  fillDataWarning: 'Please fill required fields',
  addDataWarning: 'Please add data',
  nothingFound: 'There is not any data',
  remove: 'Remove Calculation',
  pay: 'Will Pay',
  get: 'Will Get',
  total: 'Total',
  average: 'Average',
  calculationDetail: 'Calculation Detail',
  yes: 'Yes',
  no: 'No',
  areYouSureYouWantToRemoveCalculation:
    'Are you sure you want to remove this calculation?',
  wantToAddMoreExpense: 'Do you want to add expense?',
};
